// Browser acceptance harness with labelled synthetic data. No production route.
import {createServer} from 'vite'
import {mkdtempSync,mkdirSync,rmSync,writeFileSync,readFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {resolve,join} from 'node:path'
import {execFileSync} from 'node:child_process'
import assert from 'node:assert/strict'
const root=resolve('..'),folder=mkdtempSync(join(tmpdir(),'baoan-browser-')),out=resolve(root,'outputs','analytics-verification')
mkdirSync(out,{recursive:true})
execFileSync('python',['-m','tests.analytics_fixture',folder],{cwd:root,env:{...process.env,PYTHONUTF8:'1'}})
const query={mode:'drug',entity:'Ambroxol',role:'winner',months:12,start:'2026-02-01',end:'2026-03-31',comparison:'yoy',filters:{}}
const run=(action,body)=>JSON.parse(execFileSync('node',['scripts/analytics_local.mjs'],{cwd:root,input:JSON.stringify({action,body}),encoding:'utf8',env:{...process.env,ANALYTICS_DB_DIR:folder},timeout:30000}))
const data=run('overview',query),detail=Object.fromEntries(['msc_prices','msc_tenders','vss','dav'].map(source=>[source,run('detail',{query,source,page:0})]))
data.sources.msc_prices.rows.push(...Array.from({length:18},(_,i)=>({kind:'facility',period:'current',label:'Ranking scroll DEMO '+i,amount:'10',count:1})))
data.baoanCoordinates=[{ingredient_key:'ambroxol',strength_key:'75mg',group_key:'4'}]
const packageRows=detail.msc_prices.items.filter(row=>row.tender_no),awardRow=packageRows[0]?{...packageRows[0],source:'msc_prices'}:null
const awardItems=awardRow?[awardRow]:[]
const packageDetail=awardRow?run('detail',{query:{mode:'macro',entity:'',role:'winner',months:'all',comparison:'none',filters:{}},source:'msc_prices',page:0,tenderNo:awardRow.tender_no}):{items:[],hasMore:false,page:0}
const html=`<!doctype html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Analytics DEMO verification</title><style>#root{height:auto!important}</style></head><body><div id="root"></div><div id="table-fixture" style="position:relative;z-index:1000;margin-top:12px;padding:12px;background:white"></div><script>window.__data=${JSON.stringify(data)};window.__details=${JSON.stringify(detail)};window.__packageDetail=${JSON.stringify(packageDetail)};window.__awardItems=${JSON.stringify(awardItems)};window.__requests=JSON.parse(sessionStorage.getItem('analyticsTestRequests')||'[]');window.__overviewQueries=[];window.__contextQueries=[];window.__record=x=>{window.__requests.push(x);sessionStorage.setItem('analyticsTestRequests',JSON.stringify(window.__requests))};window.__clearRequests=()=>{window.__requests=[];sessionStorage.setItem('analyticsTestRequests','[]')};window.addEventListener('baoan-analytics-open',e=>window.__contextQueries.push(e.detail));if(location.search.includes('empty'))sessionStorage.removeItem('baoan.analytics.open');else sessionStorage.setItem('baoan.analytics.open',${JSON.stringify(JSON.stringify(query))});</script><script type="module">import React from 'react';import {createRoot} from 'react-dom/client';import App from '/src/analytics/AnalyticsApp.tsx';import {DataTable} from '/src/components.jsx';import '/src/styles.css';createRoot(document.getElementById('root')).render(React.createElement(App,{deep:!location.search.includes('overview')}));const columns=[{key:'registration',label:'SDK'},{key:'winner',label:'Doanh nghiệp'},{key:'province',label:'Tỉnh'},{key:'buyer',label:'Cơ sở'}];const rows=[{id:'context-demo',registration:'SDK-DEMO-001',winner:'Công ty DEMO',province:'Cần Thơ',buyer:'Bệnh viện DEMO'}];createRoot(document.getElementById('table-fixture')).render(React.createElement(DataTable,{columns,rows,rowKey:r=>r.id,showIndex:false,selectable:false,filtersVisible:false}));</script></body></html>`
const server=await createServer({root:process.cwd(),server:{port:5188,strictPort:true},plugins:[{name:'analytics-acceptance-fixtures',enforce:'pre',resolveId(id,importer){if(importer?.includes('/analytics/')&&id==='../services/regulatoryService')return '\0analytics-test-news';if(importer?.includes('/analytics/')&&id==='../auth')return '\0analytics-test-auth';if(importer?.includes('/analytics/')&&id==='../supabaseClient')return '\0analytics-test-supabase';if(importer?.includes('/analytics/')&&id==='./client')return '\0analytics-test-client'},load(id){if(id==='\0analytics-test-news')return `export const regulatoryRequest=async params=>{const r=await fetch('/api/regulatory?'+new URLSearchParams(params));return r.json()}`;if(id==='\0analytics-test-auth')return `export const useAuth=()=>({user:{id:'DEMO-user'}});`;if(id==='\0analytics-test-supabase')return `export const getSupabase=()=>({auth:{getSession:async()=>({data:{session:{access_token:'DEMO-token'}}})}});`;if(id==='\0analytics-test-client')return `export async function loadOverview(q){window.__record('overview');window.__overviewQueries.push(q);return {...window.__data,query:{...window.__data.query,...q}}}export async function loadDetail(q,s,p){window.__record('detail:'+s);return {...window.__details[s],page:p}}export async function loadCompetition(q,s,p){window.__record('competition:'+q.entity);return {...window.__details[s],page:p}}export async function loadInsight(q,manual,snapshot){window.__lastSnapshot=snapshot;window.__record('ai');return {method:'ai',provider:'DEMO',model:'acceptance-fixture',generatedAt:new Date().toISOString(),evidence:[{detail:'Dữ liệu DEMO kiểm thử.',source:'msc_prices'}],inference:[],verification:[],actions:[]}}export async function request(path,body){if(path.endsWith('/company-profile')){window.__record('profile');return {profiles:[{legalName:body.query.entity,introduction:'Synthetic legal profile DEMO',taxId:'DEMO-TAX',officeAddress:'Synthetic address',officeProvince:'Cần Thơ',factoryAddress:'Synthetic factory',factoryProvince:'Vĩnh Phúc',imageUrl:null,sourceUrls:['https://example.test/profile'],status:'synthetic'}],matchedNames:[body.query.entity]}}if(path.endsWith('/awards')){window.__record('awards');return {source:body.source,sort:body.sort,page:body.page,items:window.__awardItems,hasMore:false,totalDistinctPackages:1}}if(path.endsWith('/detail')&&body.tenderNo){window.__record('package-detail');return {source:'msc_prices',page:0,hasMore:false,items:window.__packageDetail.items}}window.__record('request:'+path);return {}}export function clearAnalyticsAux(){window.__clearRequests()}export async function loadSuggestions(q){const text=q.toLowerCase();const items=text.includes('manufacturer')?[{mode:'company',role:'manufacturer',roles:['manufacturer'],label:'Manufacturer suggestion DEMO'}]:text.includes('company')?[{mode:'company',role:'winner',label:'Company suggestion DEMO'}]:text.includes('sdk')?[{mode:'drug',role:'winner',entityField:'registration',label:'SDK-DEMO-001'}]:text.includes('facility')?[{mode:'territory',role:'winner',territoryField:'facility',label:'Bệnh viện suggestion DEMO'}]:text.includes('region')?[{mode:'territory',role:'winner',territoryField:'region',label:'Miền Tây suggestion DEMO'}]:[{mode:'drug',role:'winner',entityField:'ingredient',label:'Ambroxol'}];return {items}}export async function presets(){return []}export async function savePreset(){}export function remember(){}`},configureServer(s){s.middlewares.use(async(req,res,next)=>{if(req.url?.split('?')[0]==='/api/analytics/awards'){let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw||'{}');res.setHeader('Content-Type','application/json');res.end(JSON.stringify({source:body.source,sort:body.sort,page:body.page,items:awardItems,hasMore:false,totalDistinctPackages:1}));return}if(!req.url?.startsWith('/analytics-test'))return next();res.setHeader('Content-Type','text/html');res.end(await s.transformIndexHtml('/analytics-test',html))})}}]})
let browser
try{
 await server.listen()
 const runtime=process.env.CODEX_NODE_PACKAGES||'C:/Users/AD/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules'
 const {chromium}=await import('file:///'+runtime.replace(/\\/g,'/')+'/playwright/index.mjs')
 browser=await chromium.launch({headless:true,channel:'msedge'})
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage()
 await context.addInitScript(()=>{window.print=()=>{window.__printed=true}})
 await context.route('**/api/regulatory?**',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({items:Array.from({length:10},(_,i)=>({id:'news-'+i,title:'Tin đấu thầu DEMO '+i,summary:'Tin đã được AI thu thập để kiểm thử hiển thị tự động. '.repeat(8),source_url:'https://example.test/news/'+i,published_at:'2026-10-09',legal_status:'unknown'}))})}))
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('http://localhost:5188/analytics-test')
 await page.getByRole('heading',{name:'Phân tích tổng hợp',exact:true}).first().waitFor()
 await page.getByText('340,75 ₫',{exact:true}).first().waitFor()
 await page.screenshot({path:join(out,'desktop.png')});await page.screenshot({path:join(out,'desktop-full.png'),fullPage:true});await page.waitForTimeout(1600);await page.locator('.analytics-grid').first().screenshot({path:join(out,'group-tender.png')});await page.locator('.analytics-unit-comparison').locator('..').screenshot({path:join(out,'unit-comparison.png')})
 assert.equal(await page.evaluate(()=>window.__requests.filter(x=>x.startsWith('detail')).length),0)
 await page.getByRole('button',{name:'N4',exact:true}).first().click();assert.equal(await page.getByRole('button',{name:'N4',exact:true}).first().getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'N4',exact:true}).first().click();assert.equal(await page.getByRole('button',{name:'N4',exact:true}).first().getAttribute('aria-pressed'),'false')
 await page.getByRole('button',{name:'Mở bảng · 50 dòng/trang',exact:true}).first().click()
 await page.getByText('Ambroxol DEMO',{exact:true}).first().waitFor()
 assert.equal(await page.evaluate(()=>window.__requests.filter(x=>x.startsWith('detail')).length),1)
 await page.getByText('Dữ liệu DEMO kiểm thử.',{exact:false}).first().waitFor()
 assert.ok(await page.evaluate(()=>window.__requests.includes('ai')),'AI insight should load automatically without clicking the analysis button')
 await page.getByText('DEMO · acceptance-fixture',{exact:true}).waitFor()
 const help=page.locator('.analytics-help').first();await help.hover();const tooltip=page.locator('.analytics-tooltip:visible').first();await tooltip.waitFor();assert.ok((await tooltip.innerText()).length>8,'hover should reveal the actual metric hint')
 await page.getByRole('button',{name:'Ghim báo cáo Ambroxol'}).click()
 await page.getByRole('heading',{name:'Tin đấu thầu DEMO 0',exact:true}).first().waitFor()
 assert.equal(await page.getByRole('button',{name:'Mở tin đã thu thập'}).count(),0)
 const headings=await page.locator('.analytics-report h2').allTextContents();assert.ok(headings.findIndex(s=>s.startsWith('Ma trận đối thủ'))<headings.findIndex(s=>s.startsWith('DM93')));assert.ok(headings.findIndex(s=>s.startsWith('DM93'))<headings.findIndex(s=>s.startsWith('Tin đấu thầu')))
 assert.equal(await page.locator('.analytics-detail-grid .analytics-card').count(),4)
 const unitCard=page.locator('#analytics-co-cau-gia-tri-trung-thau-theo-don-vi')
 assert.match(await unitCard.locator('.analytics-unit-chart').first().innerText(),/^Kỳ đối chiếu/)
 assert.ok(await unitCard.locator('.analytics-unit-chart').last().evaluate(node=>node.classList.contains('analytics-unit-current')))
 const unit=unitCard.locator('.analytics-legend-button').first()
 await unit.click();assert.equal(await unit.getAttribute('aria-pressed'),'true')
 await unit.click();assert.equal(await unit.getAttribute('aria-pressed'),'false')
 await unit.click();await page.getByRole('heading',{name:'Phân tích tổng hợp',exact:true}).click();assert.equal(await unit.getAttribute('aria-pressed'),'false')
 const popupPromise=page.waitForEvent('popup')
 await page.getByRole('button',{name:'In / Xuất PDF',exact:true}).click()
 const preview=await popupPromise;await preview.waitForFunction(()=>window.__printed)
 assert.equal(await preview.locator('button').count(),0)
 assert.equal(await preview.getByText('Các chỉ số cần bổ sung nguồn',{exact:true}).count(),0)
 assert.equal(await preview.locator('.analytics-detail-grid .analytics-card').count(),1,'closed details must be omitted from print')
 assert.ok(await preview.locator('.analytics-export-more').count()>0)
 assert.ok((await preview.locator('.analytics-export-more').first().getAttribute('href')).includes('analyticsSection='))
 await preview.setViewportSize({width:1122,height:792});await preview.emulateMedia({media:'print'})
 await preview.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))))
 const printGeometry=await preview.locator('.analytics-trend').evaluateAll(nodes=>nodes.map(node=>({width:node.clientWidth,math:[...node.querySelectorAll('.analytics-math,.analytics-trend-heading,.analytics-table,table')].map(child=>({class:child.className,client:child.clientWidth,scroll:child.scrollWidth,rect:child.getBoundingClientRect().toJSON()}))})))
 assert.ok(printGeometry.every(panel=>panel.math.every(node=>node.scroll<=node.client+1)),'printed trend tables must fit their cards')
 assert.ok(await preview.locator('img[data-analytics-chart]').evaluateAll(nodes=>nodes.length>0&&nodes.every(img=>img.complete&&img.naturalWidth>0)),'print must retain every SVG chart')
 writeFileSync(join(out,'analytics-print.html'),await preview.content())
 await preview.pdf({path:join(out,'analytics-demo-report.pdf'),preferCSSPageSize:true,printBackground:true})
 await preview.screenshot({path:join(out,'print-preview.png'),fullPage:true})
 await preview.close()
 const downloadPromise=page.waitForEvent('download')
 await page.getByRole('button',{name:'Tải HTML',exact:true}).click()
 const download=await downloadPromise;await download.saveAs(join(out,'analytics-demo-report.html'))
 const exported=readFileSync(join(out,'analytics-demo-report.html'),'utf8')
 assert.ok(exported.includes('recharts-surface'));assert.ok(exported.includes('max-height:none!important'))
 assert.ok(!exported.includes('<script'),'HTML must be a standalone snapshot without scripts')
 const htmlPage=await context.newPage();await htmlPage.setContent(exported)
 assert.equal(await htmlPage.locator('.analytics-help-wrap').count(),0)
 assert.equal(await htmlPage.locator('button').count(),0)
 await htmlPage.screenshot({path:join(out,'html-preview.png'),fullPage:true});await htmlPage.close()
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(out,'mobile.png')})
 const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)
 await page.setViewportSize({width:1440,height:1000})
 await page.getByRole('button',{name:'Mở ma trận đối thủ',exact:true}).click()
 const rivalName=page.getByText('Đối thủ DEMO',{exact:true}).first();await rivalName.waitFor()
 await rivalName.dblclick();await page.getByRole('dialog').waitFor();await page.getByRole('heading',{name:'Kết quả trúng thầu gần đây'}).waitFor();await page.getByRole('button',{name:'Đóng'}).click()
 await rivalName.click({button:'right'});const rivalMenu=page.getByRole('menu',{name:'Phân tích đối tượng'});await rivalMenu.waitFor();await rivalMenu.locator('[role="menuitem"]').click()
 await page.waitForFunction(()=>window.__contextQueries.at(-1)?.entity==='Đối thủ DEMO')
 const rivalContext=await page.evaluate(()=>window.__contextQueries.at(-1));assert.equal(rivalContext.mode,'company');assert.equal(rivalContext.role,'all');assert.notEqual(rivalContext.companyFocus,'manufacturer')
 assert.equal(await page.getByLabel('Loại chủ thể').count(),0)
 assert.equal(await page.getByRole('dialog').count(),0,'company context analysis should navigate without a confirmation dialog')
 const input=page.getByRole('combobox',{name:'Tìm thuốc, doanh nghiệp, địa bàn'})
 const choose=async(text,label)=>{await input.fill(text);const option=page.getByRole('option',{name:new RegExp(label)});await option.waitFor();await option.click();await page.getByRole('button',{name:'Áp dụng',exact:true}).click();await page.waitForFunction(value=>window.__overviewQueries.at(-1)?.entity===value,label)}
 await choose('company search','Company suggestion DEMO');assert.equal(await page.evaluate(()=>window.__overviewQueries.at(-1).mode),'company');assert.equal(await page.evaluate(()=>window.__overviewQueries.at(-1).companyFocus),'business');assert.equal(await page.evaluate(()=>window.__overviewQueries.at(-1).entityMatch),'contains');await page.getByText('Synthetic legal profile DEMO',{exact:true}).waitFor();await page.locator('#analytics-ket-qua-trung-thau-gan-day').screenshot({path:join(out,'recent-awards.png')});await page.locator('.analytics-detail-grid').screenshot({path:join(out,'detail-cards.png')})
 await choose('manufacturer search','Manufacturer suggestion DEMO');assert.equal(await page.evaluate(()=>window.__overviewQueries.at(-1).mode),'company');assert.equal(await page.evaluate(()=>window.__overviewQueries.at(-1).companyFocus),'manufacturer')
 await choose('sdk search','SDK-DEMO-001');assert.equal(await page.evaluate(()=>window.__overviewQueries.at(-1).entityField),'registration')
 await choose('facility search','Bệnh viện suggestion DEMO');assert.equal(await page.evaluate(()=>window.__overviewQueries.at(-1).territoryField),'facility')
 await choose('region search','Miền Tây suggestion DEMO');assert.equal(await page.evaluate(()=>window.__overviewQueries.at(-1).territoryField),'region')
 assert.ok(await page.locator('.analytics-report-tabs>div').count()>=4,'searches should retain distinct report tabs')
 await page.locator('.analytics-report-tabs button').filter({hasText:'Company suggestion DEMO'}).click()
 await page.waitForFunction(()=>document.querySelector('.analytics-report-tabs>div.active')?.innerText.includes('Company suggestion DEMO'))
 assert.equal(await page.locator('.analytics-report-tabs>div.active').innerText(),'Company suggestion DEMO')
 await page.locator('.analytics-report-tabs [aria-label="Đóng báo cáo Company suggestion DEMO"]').click()
 assert.equal(await page.locator('.analytics-report-tabs>div').filter({hasText:'Company suggestion DEMO'}).count(),0)
 await page.getByRole('button',{name:'Quay lại',exact:false}).click()
 await page.locator('.analytics-app [aria-busy="true"]').waitFor({state:'hidden'})
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))))
 const contextCases=[
  {cell:'SDK-DEMO-001',expected:{mode:'drug',entity:'SDK-DEMO-001',role:'winner',entityField:'registration',territoryField:'province'}},
  {cell:'Công ty DEMO',expected:{mode:'company',entity:'Công ty DEMO',role:'all',entityField:'ingredient',territoryField:'province'}},
  {cell:'Cần Thơ',expected:{mode:'territory',entity:'Cần Thơ',role:'winner',entityField:'ingredient',territoryField:'province'}},
  {cell:'Bệnh viện DEMO',expected:{mode:'territory',entity:'Bệnh viện DEMO',role:'winner',entityField:'ingredient',territoryField:'facility'}},
 ]
 for(const {cell,expected} of contextCases){
  const target=page.getByRole('cell',{name:cell,exact:true});await target.scrollIntoViewIfNeeded();await target.click({button:'right'})
  const menu=page.getByRole('menu',{name:'Phân tích đối tượng'});await menu.waitFor()
  assert.match(await menu.innerText(),/Phân tích ·/)
  await menu.locator('[role="menuitem"]').click()
  const opened=await page.evaluate(()=>{const q=window.__contextQueries.at(-1);return q&&{mode:q.mode,entity:q.entity,role:q.role,entityField:q.entityField,territoryField:q.territoryField}})
  assert.deepEqual(opened,expected,`context menu should preserve typed mapping for ${cell}`)
 }
 const keyboardCell=page.getByRole('cell',{name:'SDK-DEMO-001',exact:true});await keyboardCell.focus();await keyboardCell.press('Shift+F10')
 await page.getByRole('menu',{name:'Phân tích đối tượng'}).waitFor();await page.keyboard.press('Escape');await page.getByRole('menu',{name:'Phân tích đối tượng'}).waitFor({state:'detached'})
 await page.getByRole('cell',{name:'Cần Thơ',exact:true}).click({button:'right',force:true});await page.getByRole('menu',{name:'Phân tích đối tượng'}).waitFor();await page.locator('body').click({position:{x:8,y:8}});await page.getByRole('menu',{name:'Phân tích đối tượng'}).waitFor({state:'detached'})
 const rankingEntity=page.locator('.analytics-ranking .analytics-entity-value').first();await rankingEntity.scrollIntoViewIfNeeded();await rankingEntity.click({button:'right'});const rankMenu=page.getByRole('menu',{name:'Phân tích đối tượng'});await rankMenu.waitFor();assert.match(await rankMenu.innerText(),/Phân tích ·/);await rankMenu.locator('[role="menuitem"]').click()
 const relatedEntity=page.locator('.analytics-ranking .analytics-entity-value').first();await relatedEntity.waitFor();await relatedEntity.dblclick();await page.getByRole('dialog').waitFor();await page.getByRole('heading',{name:'Kết quả trúng thầu gần đây'}).waitFor();await page.locator('.analytics-package-awards tbody tr td:first-child').first().dblclick();await page.getByRole('heading',{name:/Danh sách thuốc trong gói/}).waitFor();assert.equal(await page.getByRole('dialog').count(),1,'package details should stay in the same modal');assert.ok(await page.locator('.analytics-package-layout.has-package').count(),'related package view should show both panes')
 await page.getByRole('button',{name:'Đóng'}).click()
 const otherTab=page.locator('.analytics-report-tabs>div:not(.active) button:first-child').first();await otherTab.click()
 await page.evaluate(()=>{window.__realNow=Date.now;Date.now=()=>window.__realNow()+6*60*1000;window.__clearRequests()})
 await page.locator('.analytics-report-tabs button').filter({hasText:'Ambroxol'}).first().click();await page.locator('.analytics-report').waitFor();assert.deepEqual(await page.evaluate(()=>window.__requests.filter(x=>['overview','ai'].includes(x))),[],'returning to a cached tab after five minutes should not recompute it')
 const lockedPage=await context.newPage();await lockedPage.goto('http://localhost:5188/analytics-test?empty');await lockedPage.getByRole('heading',{name:'Phân tích tổng hợp',exact:true}).first().waitFor();const restoredTab=lockedPage.locator('.analytics-report-tabs>div').filter({hasText:'Ambroxol'}).locator('button').first();await restoredTab.click();await lockedPage.locator('.analytics-report').waitFor();await lockedPage.getByText('340,75 ₫',{exact:true}).first().waitFor();assert.deepEqual(await lockedPage.evaluate(()=>window.__requests.filter(x=>['overview','ai'].includes(x))),[],'a locked report should restore in a fresh tab without overview or AI calls')
 await lockedPage.evaluate(()=>{const key='baoan.analytics.locked.DEMO-user',all=JSON.parse(localStorage.getItem(key));for(const record of Object.values(all))delete record.analysisRevision;localStorage.setItem(key,JSON.stringify(all));for(const key of Object.keys(sessionStorage))if(key.startsWith('baoan.analytics.report.'))sessionStorage.removeItem(key);window.__clearRequests()});await lockedPage.reload();await lockedPage.locator('.analytics-report-tabs>div').filter({hasText:'Ambroxol'}).locator('button').first().click();await lockedPage.waitForFunction(()=>window.__requests.includes('ai'));assert.ok(!await lockedPage.evaluate(()=>window.__requests.includes('overview')),'upgrading locked analysis must keep the stored facts');assert.equal(await lockedPage.evaluate(()=>window.__lastSnapshot.generatedAt),data.generatedAt)
 await lockedPage.getByLabel('Từ').fill('2026-02-02');await lockedPage.getByRole('button',{name:'Áp dụng',exact:true}).click();await lockedPage.waitForFunction(()=>window.__overviewQueries.some(q=>q.start==='2026-02-02'));await lockedPage.waitForFunction(()=>window.__requests.includes('ai'));assert.ok(await lockedPage.evaluate(()=>window.__requests.includes('overview')),'editing a locked report date should compute a fresh report');await lockedPage.close()
 const linkedPage=await context.newPage();const section='analytics-msc-don-gia-ho-so-chi-tiet'
 await linkedPage.goto('http://localhost:5188/analytics-test?analyticsReport='+encodeURIComponent(JSON.stringify(query))+'&analyticsSection='+section)
 await linkedPage.locator('#'+section+' [aria-expanded=true]').waitFor();await linkedPage.locator('#'+section+' tbody tr').first().waitFor();await linkedPage.close()
 await page.goto('http://localhost:5188/analytics-test?overview')
 await page.getByRole('heading',{name:'Phân tích tổng hợp',exact:true}).first().waitFor()
 assert.equal(await page.getByRole('button',{name:'Mở bảng · 50 dòng/trang'}).count(),0)
 assert.deepEqual(errors,[])
 await page.evaluate(()=>window.__clearRequests());await page.goto('http://localhost:5188/analytics-test?empty')
 await page.getByRole('heading',{name:'Phân tích tổng hợp',exact:true}).first().waitFor();await page.waitForTimeout(300)
 assert.equal(await page.evaluate(()=>window.__requests.length),0,'empty deep-drug initialization should not request overview, AI, or details')
 await page.getByRole('button',{name:'Phân tích mới',exact:true}).click();await page.waitForTimeout(300)
 assert.equal(await page.evaluate(()=>window.__requests.length),0,'changing the empty deep-analysis mode should preserve guidance without fetching data')
 await page.evaluate(()=>window.__clearRequests());await page.goto('http://localhost:5188/analytics-test?empty-overview')
 await page.getByRole('heading',{name:'Phân tích tổng hợp',exact:true}).first().waitFor();await page.waitForTimeout(300)
 assert.equal(await page.evaluate(()=>window.__requests.length),0,'empty macro should remain guidance-only until Apply')
 await page.getByRole('button',{name:'Áp dụng',exact:true}).click()
 await page.waitForFunction(()=>window.__overviewQueries.length>0)
 const explicitMacro=await page.evaluate(()=>{const q=window.__overviewQueries.at(-1);return {mode:q.mode,entity:q.entity}})
 assert.deepEqual(explicitMacro,{mode:'macro',entity:''},'explicit Apply may request a whole-market macro overview')
 assert.ok(!await page.evaluate(()=>window.__requests.some(x=>x.startsWith('detail'))),'empty macro Apply should not load detail tables automatically')
 await page.getByRole('button',{name:'ALL',exact:true}).click();assert.equal(await page.getByLabel('Từ').isDisabled(),true);assert.equal(await page.getByLabel('Đến').isDisabled(),true,'ALL must disable custom date boundaries')
 writeFileSync(join(out,'browser-results.json'),JSON.stringify({passed:!mobileOverflow,mobileOverflow,checks:['desktop','mobile','lazy detail','automatic AI','screen print/PDF and standalone HTML','unit reset on repeat/outside click','automatic news','locked revision upgrade with stored facts','CompetitionMatrix company right-click analysis and double-click related awards','typed company/SDK/facility/region suggestions','context back','overview','DataTable context menu right-click and Shift+F10/Escape','typed SDK/company/province/facility context navigation','empty deep guidance and no fetch','empty macro guidance then explicit Apply'],errors},null,2))
 assert.ok(!mobileOverflow,'mobile must not overflow horizontally')
 console.log('Browser acceptance passed; screenshots and PDF saved in outputs/analytics-verification.')
}finally{await browser?.close();await server.close();rmSync(folder,{recursive:true,force:true})}
