"""Build the self-contained bookmarklet instruction page from maintained JS."""
from pathlib import Path
from urllib.parse import quote
from html import escape

root=Path(__file__).resolve().parent
script=(root/'collector.js').read_text(encoding='utf-8')
bookmark='javascript:'+quote(script,safe='')
html='''<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Thu thập gói thầu thuốc</title><style>body{font:17px/1.65 Segoe UI,sans-serif;color:#15333f;background:#edf4f6;margin:0}main{max-width:850px;margin:45px auto;padding:35px;background:white;border-radius:16px}h1{font-size:30px}a{color:#155e75}.bookmark{display:inline-block;background:#155e75;color:white;padding:13px 22px;border-radius:8px;text-decoration:none}li{margin:15px 0}textarea{width:100%;height:100px}small{color:#526772}</style><main><h1>Đưa gói thầu thuốc vào bộ lọc</h1><p>Đơn giá thuốc được ứng dụng tải trực tiếp. Trang gói thầu sử dụng bước xác thực trên trình duyệt; tiện ích này đọc các kết quả bạn đang xem và lưu thành JSON để nhập vào ứng dụng.</p><ol><li>Bật thanh dấu trang bằng <b>Ctrl + Shift + B</b>. Kéo nút sau lên thanh dấu trang:<br><a class="bookmark" href="BOOKMARK">Thu thập gói thầu thuốc</a></li><li>Mở <a href="https://muasamcong.mpi.gov.vn/web/guest/contractor-selection?render=index">trang lựa chọn nhà thầu</a>. Chọn tìm kiếm nâng cao → thông báo mời thầu thuốc, đặt khoảng ngày và bộ lọc cần dùng. Tìm kiếm và chờ có kết quả.</li><li>Bấm dấu trang <b>Thu thập gói thầu thuốc</b> vừa lưu. Bảng nhỏ xuất hiện ở góc phải. Nếu chưa nhận trang đầu, bấm Tìm kiếm lại.</li><li>Chọn số trang tiếp theo và bấm <b>Tự chuyển trang</b>, hoặc tự chuyển trang như bình thường. Có nút Dừng. Nếu nguồn yêu cầu đăng nhập hoặc xác minh, xử lý trực tiếp trên trang rồi chạy tiếp.</li><li>Bấm <b>Lưu JSON</b>. Quay về công cụ → <b>Nhập JSON / HAR</b> và chọn file vừa tải. ID trùng được cập nhật, không nhân đôi.</li></ol><p><b>Phạm vi:</b> chỉ các trang đã thu thập được nhập. Nếu trang nguồn giới hạn kết quả, hãy thu hẹp khoảng ngày và thu thập từng khoảng. Không tự suy ra đã có toàn bộ dữ liệu.</p><p>Tiện ích chỉ đọc phản hồi tìm kiếm công khai; không đọc cookie, mật khẩu hoặc token. Không gửi dữ liệu đến máy chủ khác. Dữ liệu chưa lưu sẽ mất khi đóng/tải lại trang.</p><details><summary>Nếu không kéo được nút vào thanh dấu trang</summary><p>Tạo dấu trang mới và dùng nội dung bên dưới làm địa chỉ. Sau đó chạy dấu trang trên trang Mua sắm công.</p><textarea readonly>BOOKMARK_TEXT</textarea></details><p><small>Cách khác: nhập HAR có nội dung phản hồi từ trình duyệt. Công cụ chỉ lấy dữ liệu JSON của đúng API Mua sắm công, không lưu cookie/header vào cơ sở dữ liệu.</small></p></main></html>'''
(root/'HUONG_DAN_TRINH_DUYET.html').write_text(html.replace('BOOKMARK_TEXT',escape(bookmark)).replace('BOOKMARK',escape(bookmark,quote=True)),encoding='utf-8')
print('Built browser helper')
