import {useCallback,useEffect,useRef,useState} from 'react'
import {ArrowLeft,Layers,X,Plus,Lock,Unlock,RefreshCw} from 'lucide-react'
import {useAuth} from '../auth'
import OmniFilterBar from './OmniFilterBar'
import DetailTable from './DetailTable'
import AiStrategicInsight from './AiStrategicInsight'
import CompanyIdentity from './CompanyIdentity'
import RecentAwards from './RecentAwards'
import PackageWorkspace from './PackageWorkspace'
import EntityValue from './EntityValue'
import RegulatoryContext from './RegulatoryContext'
import ProductRanking from './ProductRanking'
import CompetitionMatrix from './CompetitionMatrix'
import {loadOverview,remember,clearAnalyticsAux} from './client'
import {resetQueryCache} from '../queryCache'
import {Trend,GroupChart,CompanyGroups,TenderChart,PriceComparison,money,count} from './Charts'
import {Card} from './ui'
import {DEFAULT_QUERY,SOURCE_LABELS} from './types'
import type {AnalyticsQuery,AnalyticsOverview,Mode,Source,StrategicInsight,DetailRow} from './types'
import './analytics.css'
// Bump when analysis changes; upgrade insights while retaining saved facts.
const ANALYSIS_REVISION='2026-10-09.1'
type SavedReport={query:AnalyticsQuery;data:AnalyticsOverview;insight?:StrategicInsight;analysisRevision?:string}
const modes:Record<Mode,string>={drug:'Thuốc / Hoạt chất',company:'Doanh nghiệp',territory:'Địa bàn',macro:'Xu hướng thị trường'}
const sourceNames=Object.keys(SOURCE_LABELS) as Source[]
const fold=(s:unknown)=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase().replace(/\s+/g,' ').trim()
const reportKey=(q:AnalyticsQuery)=>[q.mode,fold(q.entity),q.mode==='company'?'all':q.role,q.entityField,q.territoryField,q.mode==='company'?(q.companyFocus||'business'):'',q.entityMatch].join('|')
const sessionReportKey=(user:string,deep:boolean,q:AnalyticsQuery)=>`baoan.analytics.report.${user}.${deep}.${encodeURIComponent(JSON.stringify(q))}`
const lockedReportsKey=(user:string)=>`baoan.analytics.locked.${user}`
function readJson<T>(storage:Storage,key:string,fallback:T):T{try{return JSON.parse(storage.getItem(key)||'null')??fallback}catch{return fallback}}
function initial(deep:boolean):AnalyticsQuery{
  try{const raw=new URLSearchParams(location.search).get('analyticsReport');if(raw){const q=JSON.parse(raw);if(q&&['drug','company','territory','macro'].includes(q.mode)&&typeof q.entity==='string'&&q.filters&&typeof q.filters==='object'&&!Array.isArray(q.filters))return q}}catch{}
  if(deep)try{const raw=sessionStorage.getItem('baoan.analytics.open');if(raw){sessionStorage.removeItem('baoan.analytics.open');const saved=JSON.parse(raw);return {...saved,role:saved.mode==='company'?'all':saved.role}}}catch{/* Optional navigation context. */}
  return {...DEFAULT_QUERY,mode:deep?'drug':'macro',filters:{}}
}
export default function AnalyticsApp({deep=false,localMode=false,onOpenDeep}:{deep?:boolean;localMode?:boolean;onOpenDeep?:()=>void}){
  const {user}=useAuth() as {user:{id:string}|null}
  const [query,setQuery]=useState<AnalyticsQuery>(()=>initial(deep)),[data,setData]=useState<AnalyticsOverview>(),[loading,setLoading]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<AnalyticsQuery[]>([]),[insight,setInsight]=useState<StrategicInsight>(),[exporting,setExporting]=useState(false),[retry,setRetry]=useState(0),[restored,setRestored]=useState(false),[tabsLoaded,setTabsLoaded]=useState(false),[locked,setLocked]=useState<string[]>([]),[analysisRevision,setAnalysisRevision]=useState<string>()
  const generation=useRef(0),root=useRef<HTMLDivElement>(null),skipCache=useRef(false),dataQuery=useRef('')
  const [activated,setActivated]=useState(()=>Boolean(query.entity||Object.values(query.filters).some(Boolean)))
  const [reports,setReports]=useState<AnalyticsQuery[]>(()=>query.entity?[query]:[])
  const tabKey=reportKey
  useEffect(()=>{if(!user?.id)return;const tabs=readJson<AnalyticsQuery[]>(sessionStorage,`baoan.analytics.tabs.${user.id}.${deep}`,[]),saved=readJson<Record<string,SavedReport>>(localStorage,lockedReportsKey(user.id),{});setLocked(Object.keys(saved));setReports(current=>[...current,...tabs,...Object.values(saved).map(v=>v.query)].filter((q,i,all)=>q&&['drug','company','territory','macro'].includes(q.mode)&&typeof q.entity==='string'&&q.filters&&all.findIndex(v=>v&&tabKey(v)===tabKey(q))===i).slice(-8));setTabsLoaded(true)},[user?.id,deep])
  useEffect(()=>{if(user?.id&&tabsLoaded)try{sessionStorage.setItem(`baoan.analytics.tabs.${user.id}.${deep}`,JSON.stringify(reports))}catch{}},[reports,user?.id,deep,tabsLoaded])
  useEffect(()=>{if(!user?.id||!data||!activated||dataQuery.current!==JSON.stringify(query))return;const record={query,data,insight,analysisRevision};try{sessionStorage.setItem(sessionReportKey(user.id,deep,query),JSON.stringify(record));if(locked.includes(tabKey(query))){const all=readJson<Record<string,typeof record>>(localStorage,lockedReportsKey(user.id),{});all[tabKey(query)]=record;localStorage.setItem(lockedReportsKey(user.id),JSON.stringify(all))}}catch{}},[data,insight,query,user?.id,deep,activated,restored,locked,analysisRevision])
  const [rankingSource,setRankingSource]=useState<Source>('msc_prices')
  const [relatedQuery,setRelatedQuery]=useState<AnalyticsQuery>(),[packageRow,setPackageRow]=useState<DetailRow>()
  const showRelated=(q:AnalyticsQuery)=>{setRelatedQuery(q);setPackageRow(undefined)}
  useEffect(()=>{const updated=()=>{resetQueryCache();clearAnalyticsAux();skipCache.current=true;setRetry(n=>n+1)};window.addEventListener('baoan-data-updated',updated);return()=>window.removeEventListener('baoan-data-updated',updated)},[])
  useEffect(()=>{
    const id=++generation.current;setLoading(true);setError('')
    if(!activated||deep&&query.mode!=='macro'&&!query.entity.trim()&&!Object.values(query.filters).some(Boolean)){setData(undefined);setInsight(undefined);setRestored(false);setLoading(false);return}
    const sk=user?.id?sessionReportKey(user.id,deep,query):'';let cached=sk?readJson<SavedReport|null>(sessionStorage,sk,null):null
    if(!cached&&user?.id){const record=readJson<Record<string,SavedReport>>(localStorage,lockedReportsKey(user.id),{});cached=record[tabKey(query)]||null}
    if(!skipCache.current&&cached?.data&&JSON.stringify(cached.query)===JSON.stringify(query)){dataQuery.current=JSON.stringify(query);setData({...cached.data,baseline:cached.insight||cached.data.baseline});setInsight(cached.insight||cached.data.baseline);setAnalysisRevision(cached.analysisRevision);setRestored(Boolean(cached.insight)&&cached.analysisRevision===ANALYSIS_REVISION);setLoading(false);return()=>{generation.current++}}
    skipCache.current=false
    setRestored(false);setAnalysisRevision(undefined);setInsight(undefined);setData(undefined)
    loadOverview(query).then(v=>{if(generation.current===id){dataQuery.current=JSON.stringify(query);setData(v);if(user?.id)remember(query,user.id)}}).catch(e=>{if(generation.current===id)setError(e.message)}).finally(()=>{if(generation.current===id)setLoading(false)})
    return()=>{generation.current++}
  },[query,retry,user?.id,deep,activated])
  const apply=(q:AnalyticsQuery)=>{q={...q,role:q.mode==='company'?'all':q.role};setActivated(true);setQuery({...q,filters:{...q.filters}});setReports(t=>t.some(v=>tabKey(v)===tabKey(q))?t.map(v=>tabKey(v)===tabKey(q)?q:v):[...t,q].slice(-8))}
  const refreshReport=()=>{if(!activated)return;if(user?.id){try{sessionStorage.removeItem(sessionReportKey(user.id,deep,query));const all=readJson<Record<string,unknown>>(localStorage,lockedReportsKey(user.id),{});delete all[tabKey(query)];localStorage.setItem(lockedReportsKey(user.id),JSON.stringify(all))}catch{}}resetQueryCache();clearAnalyticsAux();skipCache.current=true;setData(undefined);setInsight(undefined);setRestored(false);setRetry(n=>n+1)}
  const toggleLock=(q:AnalyticsQuery)=>{if(!user?.id)return;const key=tabKey(q),all=readJson<Record<string,SavedReport>>(localStorage,lockedReportsKey(user.id),{});if(locked.includes(key)){delete all[key];setLocked(v=>v.filter(k=>k!==key))}else{const cached=readJson<SavedReport|null>(sessionStorage,sessionReportKey(user.id,deep,q),null);const report=cached||(tabKey(query)===key&&data?{query,data,insight,analysisRevision}:null);if(report)all[key]=report;setLocked(v=>[...v,key])}try{localStorage.setItem(lockedReportsKey(user.id),JSON.stringify(all))}catch{}}
  const navigate=(q:AnalyticsQuery)=>{
    if(!deep){try{sessionStorage.setItem('baoan.analytics.open',JSON.stringify(q))}catch{}if(onOpenDeep){onOpenDeep();return}window.location.hash='analytics-deep';window.dispatchEvent(new CustomEvent('baoan-analytics-open',{detail:q}));return}
    setHistory(h=>[...h,query].slice(-20));apply(q)
  }
  useEffect(()=>{if(!deep)return;const open=(e:Event)=>{try{sessionStorage.removeItem('baoan.analytics.open')}catch{}navigate((e as CustomEvent<AnalyticsQuery>).detail)};window.addEventListener('baoan-analytics-open',open);return()=>window.removeEventListener('baoan-analytics-open',open)},[deep,query])
  const openEntity=(mode:'drug'|'company'|'territory',entity:string,role:AnalyticsQuery['role']='winner',field:'ingredient'|'name'|'registration'|'province'|'facility'|'region'='ingredient',companyFocus?:string)=>{
    if(!entity)return
    const next:AnalyticsQuery={...query,mode,entity,entityField:['ingredient','name','registration'].includes(field)?field as AnalyticsQuery['entityField']:'ingredient',territoryField:['province','facility','region'].includes(field)?field as AnalyticsQuery['territoryField']:'province',role:mode==='company'?'all':role,companyFocus:mode==='company'?(role==='manufacturer'||companyFocus==='manufacturer'?'manufacturer':'business'):undefined,entityMatch:mode==='company'?'contains':'exact',filters:{...query.filters}}
    navigate(next)
  }
  const rival=(r:DetailRow)=>Boolean(data?.baoanCoordinates?.some(c=>fold(c.ingredient_key)===fold(r.ingredient)&&fold(c.strength_key)===fold(r.strength)&&c.group_key===r.group_key))
  async function exportReport(){if(!data||!root.current||loading)return;const preview=window.open('','_blank');if(!preview){setError('Cho phép cửa sổ mới để mở bản in.');return}setExporting(true);try{const {exportPdf}=await import('./pdf');await exportPdf(root.current,query,preview)}catch(e){preview.close();setError((e as Error).message)}finally{setExporting(false)}}
  async function downloadHtml(){if(!data||!root.current||loading)return;try{const {exportHtml}=await import('./pdf');exportHtml(root.current,query)}catch(e){setError((e as Error).message)}}
  const acceptInsight=useCallback((value:StrategicInsight|undefined,complete=false)=>{setInsight(value);if(complete)setAnalysisRevision(ANALYSIS_REVISION)},[])
  useEffect(()=>{const section=new URLSearchParams(location.search).get('analyticsSection');if(data&&section){requestAnimationFrame(()=>document.getElementById(section)?.scrollIntoView({block:'start'}))}},[data])
  const newReport=()=>{setActivated(false);setQuery({...DEFAULT_QUERY,mode:deep?'drug':'macro',filters:{}});setInsight(undefined);setData(undefined);setRestored(false)}
  const closeReport=(q:AnalyticsQuery)=>{const remaining=reports.filter(v=>tabKey(v)!==tabKey(q));setReports(remaining);if(tabKey(query)===tabKey(q)){if(remaining.length){setQuery(remaining[remaining.length-1]);setActivated(true)}else newReport()}}
  const stats=data?.sources
  const companyFocus=(data as (AnalyticsOverview&{companyFocus?:string})|undefined)?.companyFocus||((data?.query as AnalyticsQuery&{companyFocus?:string}|undefined)?.companyFocus)
  const manufacturerFocus=query.mode==='company'&&(companyFocus||query.companyFocus)==='manufacturer'
  const rankingPanels=[{kind:query.mode==='drug'&&query.entity?'product':'ingredient',title:query.mode==='drug'&&query.entity?'Sản phẩm dẫn đầu · hàm lượng và quy cách':'Hoạt chất dẫn đầu'},...(query.mode==='company'?[{kind:manufacturerFocus?'company':'manufacturer',title:manufacturerFocus?'Khách hàng dẫn đầu':'Nhà sản xuất dẫn đầu'}]:[{kind:'company',title:'Nhà thầu dẫn đầu'}]),{kind:query.mode==='territory'?'manufacturer':'province',title:query.mode==='territory'?'Nhà sản xuất (xưởng) dẫn đầu':'Địa bàn trọng điểm'},{kind:'facility',title:'Cơ sở y tế'}]
  const metricHints:Record<Source,string>={msc_prices:'Tổng đơn giá × số lượng trên các dòng trúng thầu MSC trong kỳ; không phải đơn giá bình quân.',msc_tenders:'Tổng giá gói thầu công bố của các gói liên kết, mỗi mã gói tính một lần.',vss:'Giá trị trúng thầu ghi nhận trong VSS theo ngày hiệu lực hợp đồng; không phải tiền đã thanh toán.',dav:manufacturerFocus?'Tổng SĐK riêng biệt do nhà sản xuất đứng tên, gồm còn hạn, hết hạn và chưa rõ hạn.':'Số đăng ký còn hạn có ngày hết hạn xác định tại ngày cuối kỳ; phân tích địa bàn DAV dùng địa chỉ đơn vị đăng ký đã xác minh, chưa bao phủ đơn vị chưa xác định địa chỉ.'}
  return <div ref={root} className="analytics-app an:gap-4">
    <div className="analytics-heading"><div><h1><Layers size={22}/> Phân tích tổng hợp</h1><p className="muted">Đối chiếu MSC · VSS · DAV trên cùng bộ lọc · {localMode?'Dữ liệu local':'Dữ liệu cloud'}</p></div>{history.length>0&&<button className="btn ghost" onClick={()=>{const previous=history[history.length-1];setHistory(h=>h.slice(0,-1));apply(previous)}}><ArrowLeft size={16}/>Quay lại</button>}<div className="analytics-report-tabs" aria-label="Các báo cáo đang mở">{reports.map(q=><div key={tabKey(q)} className={activated&&tabKey(q)===tabKey(query)?'active':''}><button aria-pressed={activated&&tabKey(q)===tabKey(query)} onClick={()=>apply(q)} title={`${modes[q.mode]}: ${q.entity||'Toàn thị trường'}`}>{q.entity||'Toàn thị trường'}</button><button type="button" className="analytics-report-lock" aria-label={`${locked.includes(tabKey(q))?'Bỏ ghim':'Ghim'} báo cáo ${q.entity||'Toàn thị trường'}`} aria-pressed={locked.includes(tabKey(q))} onClick={()=>toggleLock(q)}>{locked.includes(tabKey(q))?<Lock size={13}/>:<Unlock size={13}/>}</button><button aria-label={`Đóng báo cáo ${q.entity||'Toàn thị trường'}`} onClick={()=>closeReport(q)}><X size={13}/></button></div>)}<button className="btn ghost" onClick={newReport} title="Mở phân tích mới" aria-label="Phân tích mới"><Plus size={16}/></button></div></div>
    <OmniFilterBar query={query} onApply={apply} onExport={exportReport} onExportHtml={downloadHtml} exporting={exporting||loading}/>
    <div className="analytics-context">{activated&&query.entity&&<span><span className="analytics-context-type">{modes[query.mode]}</span> <strong>{query.entity}</strong></span>}<span className="analytics-context-actions">{activated&&<button className="btn ghost" disabled={loading} onClick={refreshReport}><RefreshCw size={14}/>Cập nhật báo cáo</button>}{localMode&&<button className="analytics-link" onClick={()=>window.dispatchEvent(new Event('baoan-open-data'))}>Tải dữ liệu production về local ↗</button>}</span></div>
    {!activated&&<div className="analytics-guidance"><strong>Tìm chủ thể để bắt đầu</strong><p>Nhập hoạt chất, tên thuốc, SĐK, doanh nghiệp, tỉnh hoặc cơ sở y tế. Chọn gợi ý và bấm Áp dụng; loại chủ thể được nhận diện tự động. Giữ ô trống và bấm Áp dụng để xem toàn thị trường.</p></div>}
    {loading&&<p role="status">Đang tổng hợp dữ liệu…{data?' Giữ báo cáo trước trong lúc tải.':''}</p>}{error&&<p role="alert">{error} <button className="btn ghost" onClick={refreshReport}>Thử lại</button></p>}
    {activated&&<AiStrategicInsight query={query} onResult={acceptInsight} snapshot={data} baseline={restored?insight:loading?undefined:data?.baseline} enabled={!loading&&!!data&&!restored} canRefresh={!loading&&!!data}/>}
    {activated&&data&&stats&&<div aria-busy={loading} className={loading?'analytics-stale':'analytics-report'}>
      <p className="muted small">{data.query.months==='all'?`Toàn bộ thời gian đến ${data.query.end}`:`${data.query.start} → ${data.query.end}`}  · {data.query.months==='all'?'ALL · Không đối chiếu':<>Đối chiếu {data.query.previousStart} → {data.query.previousEnd}</>} · Tạo lúc {new Date(data.generatedAt).toLocaleString('vi-VN',{timeZone:'Asia/Bangkok'})} {data.snapshot?'· Snapshot R2':data.cached?'· Đã lưu tạm':''}.</p>
      {sourceNames.some(s=>stats[s].comparisonMissing)&&query.comparison==='yoy'&&<div className="analytics-note">Một số nguồn không có số đối chiếu cùng kỳ. Bạn có thể xem kỳ liền trước. <button className="btn ghost" onClick={()=>apply({...query,comparison:'previous'})}>Đổi sang kỳ liền trước</button></div>}
      <div className="analytics-kpis">{sourceNames.filter(source=>!(source==='vss'&&manufacturerFocus&&stats.vss.status==='available'&&!stats.vss.rows.some(r=>r.kind==='summary'&&Number(r.count)>0))).map(source=>{const s=stats[source],current=s.rows.find(r=>r.kind==='summary'&&r.period==='current'),previous=s.rows.find(r=>r.kind==='summary'&&r.period==='previous');const regCurrent=s.rows.find(r=>r.kind==='total_registrations'&&r.period==='current'),regPrevious=s.rows.find(r=>r.kind==='total_registrations'&&r.period==='previous');const regValue=(row:typeof current|typeof regCurrent)=>{const v=row as (typeof current&{total_registrations?:number|null})|undefined;return v?.total_registrations??v?.count??v?.amount};const metricCurrent=source==='dav'&&manufacturerFocus?regValue(regCurrent)||regValue(current):current?.amount,metricPrevious=source==='dav'&&manufacturerFocus?regValue(regPrevious)||regValue(previous):previous?.amount;const growth=metricPrevious!=null&&Number(metricPrevious)>0&&metricCurrent!=null?(Number(metricCurrent)/Number(metricPrevious)-1)*100:null;return <Card exportable={s.status==='available'&&s.rows.some(r=>r.period==='current'&&Number(r.count)>0)} key={source} title={SOURCE_LABELS[source]} hint={metricHints[source]}>{s.status!=='available'?<p>{s.reason}</p>:<><p className="analytics-number">{source==='dav'&&manufacturerFocus?count(metricCurrent??0):source==='dav'?count(current?.active??0):money(current?current.amount:0)}</p><p>{source==='dav'?manufacturerFocus?'SĐK của nhà sản xuất':'SĐK còn hạn có ngày xác định':source==='msc_tenders'?'Giá gói thầu công bố':'Giá trị trúng thầu'}</p><small>{count(current?.count??0)} bản ghi</small>{source==='msc_prices'&&query.mode==='company'&&<p className="analytics-award-count">{count(current?.won_packages??0)} gói trúng · mã TBMT riêng</p>}{growth!=null?<p className={`analytics-delta ${growth>0?'positive':growth<0?'negative':'neutral'}`}><strong>{growth>0?'↑ +':growth<0?'↓ ':''}{growth.toFixed(1)}%</strong><span>so với kỳ đối chiếu</span></p>:source!=='dav'&&<p className="muted small">Chưa có cơ sở tính tăng trưởng</p>}{s.updatedAt&&<small>Cập nhật nguồn: {new Date(s.updatedAt).toLocaleString('vi-VN')}</small>}{source==='dav'&&<div className="analytics-dav-badges"><span className="new" title="SĐK được cấp trong 12 tháng tính đến ngày cuối kỳ">Cấp mới 12 tháng <b>{count(current?.new_registrations??0)}</b></span><span className="expiring" title="SĐK còn hiệu lực và hết hạn trong 18 tháng tiếp theo">Hết hạn 18 tháng <b>{count(current?.expiring??0)}</b></span><span className="unknown" title="Hồ sơ chưa có ngày hết hạn xác định; không tính là SĐK còn hạn">Chưa rõ hạn <b>{count(current?.unknown_expiry??0)}</b></span></div>}</>}</Card>})}</div>
      {query.mode==='company'&&<><CompanyIdentity query={query}/><RecentAwards query={query} onOpenPackage={row=>{setRelatedQuery(query);setPackageRow(row)}} onRelated={showRelated}/></>}
      <Trend stats={stats.msc_prices} source="msc_prices"/>
      <div className="analytics-grid">{query.mode==='company'?<CompanyGroups stats={stats.msc_prices}/>:<GroupChart stats={stats.msc_prices}/>}<TenderChart stats={stats.msc_tenders}/></div>
      <Trend stats={stats.vss} source="vss"/>
      <PriceComparison stats={stats.msc_prices} query={data.query}/>
      <div className="analytics-ranking-toolbar"><strong title="Top 30 theo giá trị trúng thầu trong kỳ, riêng từng nguồn">Xếp hạng theo giá trị</strong><div role="group" aria-label="Nguồn xếp hạng">{(['msc_prices','vss'] as Source[]).map(s=><button key={s} className="analytics-chip" aria-pressed={rankingSource===s} onClick={()=>setRankingSource(s)}>{s==='msc_prices'?'MSC':'VSS'}</button>)}</div></div>
      {query.mode==='drug'&&query.entity&&<ProductRanking query={data.query} source={rankingSource} onRelated={showRelated}/>}
      <div className="analytics-grid">{rankingPanels.filter(panel=>panel.kind!=='product').map(({kind,title})=><Card exportable={stats[rankingSource].rows.some(r=>r.kind===kind&&r.period==='current'&&r.label)} key={kind} title={title} hint="Xếp theo giá trị các dòng trúng thầu; nhà sản xuất ghi trên hồ sơ thuốc không xác nhận địa chỉ xưởng. Cuộn xem tối đa 30 đối tượng."><ul className="analytics-ranking" tabIndex={0} aria-label="Cuộn xem xếp hạng">{stats[rankingSource].rows.filter(r=>r.kind===kind&&r.period==='current'&&r.label).map(r=><li key={r.label}><EntityValue value={r.label} parentQuery={query} mode={kind==='ingredient'?'drug':['company','manufacturer'].includes(kind)?'company':'territory'} role={kind==='manufacturer'?'manufacturer':'winner'} field={kind==='facility'?'facility':kind==='province'?'province':'ingredient'} onRelated={showRelated}/><strong title={Number(r.amount||0).toLocaleString('vi-VN')+' ₫'}>{money(r.amount)}</strong></li>)}</ul>{!stats[rankingSource].rows.some(r=>r.kind===kind&&r.period==='current'&&r.label)&&<p className="muted">Không có xếp hạng trong phạm vi này.</p>}<small>Top 30 · {SOURCE_LABELS[rankingSource]}</small></Card>)}</div>
      {data.query.mode==='drug'&&<CompetitionMatrix query={data.query} onCompany={name=>openEntity('company',name)} onRelated={showRelated}/>}
      {data.query.mode==='drug'&&data.query.entity&&<RegulatoryContext query={data.query}/> }
      <div className="analytics-detail-grid">{sourceNames.map(source=><DetailTable key={source} query={data.query} source={source} onEntity={openEntity} onRelated={showRelated} onOpenPackage={['msc_prices','vss'].includes(source)?row=>{setRelatedQuery(query);setPackageRow({...row,source})}:undefined} isRival={data.query.mode==='company'?rival:undefined}/>)}</div>
      <Card title="Các chỉ số cần bổ sung nguồn" exportable={false}><ul>{Object.values(data.missing).map(reason=><li key={reason}>{reason}</li>)}</ul><p>Giá trị VSS thể hiện kết quả trúng thầu; không thể suy ra tiền giải ngân. Bảo đảm dự thầu chưa được phân loại từ giá gói.</p></Card>
    </div>}
    <PackageWorkspace relatedQuery={relatedQuery} scope={query} packageRow={packageRow} onOpenPackage={setPackageRow} onClose={()=>{setRelatedQuery(undefined);setPackageRow(undefined)}}/>
  </div>
}
