import {useEffect,useRef,useState} from 'react'
import {loadCompetition} from './client'
import {Card,cardId} from './ui'
import {money} from './Charts'
import EntityValue from './EntityValue'
import type {AnalyticsQuery,DetailPage,Source} from './types'
export default function CompetitionMatrix({query,onCompany,onRelated}:{query:AnalyticsQuery;onCompany:(name:string)=>void;onRelated?:(query:AnalyticsQuery)=>void}){
 void onCompany
 const [open,setOpen]=useState(()=>typeof location!=='undefined'&&new URLSearchParams(location.search).get('analyticsSection')===cardId('Ma trận đối thủ theo tọa độ thuốc')),[scope,setScope]=useState('ingredient'),[source,setSource]=useState<Source>('msc_prices'),[page,setPage]=useState(0),[data,setData]=useState<DetailPage>(),[error,setError]=useState(''),[loading,setLoading]=useState(false),generation=useRef(0)
 useEffect(()=>{setPage(0);setData(undefined)},[query,source,scope])
 useEffect(()=>{const id=++generation.current;if(!open)return;const filters={...query.filters};if(scope==='ingredient'){delete filters.strength;delete filters.form;delete filters.group}else if(scope==='strength_group')delete filters.form;setLoading(true);setError('');loadCompetition({...query,filters},source,page).then(value=>{if(generation.current===id)setData(value)}).catch(e=>{if(generation.current===id)setError(e.message)}).finally(()=>{if(generation.current===id)setLoading(false)});return()=>{generation.current++}},[query,source,scope,page,open])
 return <Card title="Ma trận đối thủ theo tọa độ thuốc" exportable={open&&!!data?.items.length}><button className="btn ghost" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{open?'Đóng ma trận':'Mở ma trận đối thủ'}</button>{open&&<><div className="analytics-controls"><select aria-label="Mức đối chiếu cạnh tranh" value={scope} onChange={e=>setScope(e.target.value)}><option value="ingredient">Cùng hoạt chất · toàn thị trường</option><option value="strength_group" disabled={!query.filters.strength||!query.filters.group}>Cùng hoạt chất + hàm lượng + nhóm</option><option value="direct" disabled={!query.filters.strength||!query.filters.form||!query.filters.group}>Đối thủ trực diện · đủ hàm lượng, dạng và nhóm</option></select><select aria-label="Nguồn ma trận" value={source} onChange={e=>setSource(e.target.value as Source)}><option value="msc_prices">Đơn giá MSC</option><option value="vss">VSS trúng thầu</option></select></div><p className="muted small">Chọn hàm lượng, dạng và nhóm trong bộ lọc để mở mức đối chiếu cụ thể.</p>{loading&&<p role="status">Đang tải ma trận…</p>}{error&&<p role="alert">{error}</p>}<div className="analytics-table"><table><thead><tr><th>Hoạt chất</th><th>Hàm lượng</th><th>Dạng bào chế</th><th>Nhóm</th><th>Đơn vị</th><th>Nhà thầu</th><th>Giá trị trúng</th></tr></thead><tbody>{data?.items.map(r=><tr key={r.id}><td>{r.ingredient}</td><td>{r.strength||'Chưa rõ'}</td><td>{r.form||'Chưa rõ'}</td><td>{r.group_key||'Chưa rõ'}</td><td>{r.unit||'Chưa rõ'}</td><td><EntityValue value={r.company} parentQuery={query} mode="company" role="winner" onRelated={onRelated}/></td><td>{money(r.amount)}</td></tr>)}</tbody></table></div><div className="analytics-controls"><button className="btn ghost" disabled={!page||loading} onClick={()=>setPage(p=>p-1)}>Trước</button><span>Trang {page+1}</span><button className="btn ghost" disabled={!data?.hasMore||loading} onClick={()=>setPage(p=>p+1)}>Sau</button></div></>}</Card>
}
